var projets = [
    {
        "titre":"v0xel",
        "description_en":"V0XEL • 2015 • <i> with Charles Poulain & Chun Hung </i> <br> <br> India is starting a great plan to create more than 100 smart cities in the very next years. Prime Minister Narendra Modi has chosen various sites and existing cities to receive those soon-to-be <i>smart cities</i>. Jaipur is the capital city of Rajhastan and has grown down a mountain. The historic center, very symetric and square-based, has expanded to the South, leading the city to build a bright new ring road around Jaipur. <br> <br> Water is very rare in this part of the world, and the monsoon is quick and not as abundant as it is in many tropical countries. The only stream running through the city is th Amanishah Nala. Born in the mountain, this little river goes down to South and, not only is it salted and non-drinkable but it also carries every piece of garbage produced by the city, or chemicals delivered by dyeing industries. <br> <br> Because smart cities only exist to deal with the issues met by existing ones, we decided to place our <i>Sierpinski Sponge</i> on this Amanishah Nala river to use it as a starting point for this utopian project. The whole smart system is actually based on this water, so precious but yet so mistreated by the rest of Jaipur. Every place generated by the fractal master plan enables to progressively treat it in order to make it pass from a poison-like liquid to a drinkable/healthy strength for the population. <br><br> • First, North West of this city is made of a treatment plant, removing the biggest pieces of rubbish and desalinating part of the water. <br> • The stream is then directed to the vast center place, where phyto-treatment enables people to bathe in it, which is very important among Indian culture. <br> • The third step directs  water to medium places, treating rainwater and sewage. <br> • This sewage actually comes back from the fourth step : places storing drinkable water underground and gathering rainwater on public basins. <br> • Those two types of water then receive different roles in the city : drinkable water is directed in the housing and working spaces while the rainwater is used to reduce the urban heat. Culturally, a stream of water is often used in India to create a natural ventilation in palaces and temples. The same logic has been used here, pumping the fresh water up the roof and then letting it pour down to the ground basins, associating to draughts to refresh the public spaces' layers. <br> • Last aspect of this water cycle is about the water that was too dirty to be decontaminated. The latter is used in solar tubes, with special algae to produce biomass energy from solar power. <br> <br> The city is imagined to gather data on water levels and salinity in order to adapt the channels debit to let the water decant long enough on every places. <br> <br> To organize urban repartition, the spaces have been thought as layers, producing public <i>voids</i> where water can run and vegetation star to grow.<br><br>",
        "description_fr":"2015 • <i> avec Charles Poulain & Chun Hung </i> <br> <br> Le Premier Ministre indien Narendra Modi a dernièrement lancé un grand projet pour l'Inde : la création de 100 nouvelles <i>smart cities</i>. Différents sites, vierges ou existants ont été choisis pour recevoir ces nouvelles cités. <br> <br> Jaipur est la capitale du Rajhastan et s'est développée au pied d'une montagne. Le centre historique, aux formes géométriques traditionnelles, s'est étendu vers le sud, d'une manière plus accidentée, incitant ainsi la ville à mettre en place une route périphérique.<br> <br> L'eau est une denrée rare dans ce pays où la mousson est très brève et bien moins abondante que dans les pays voisins. De plus, la seul cours d'eau traversant la ville est l'Amanishah Nala. Prenant source au cœur de la montagne, cette petite rivière chemine vers le sud et, non contente d'être salée et impropre à la consommation, elle sert également de décharge à tous les déchets du centre-ville et aux rejets polluants des nombreuses industries d'encre de teinture. <br> <br> Si les smart cities ont bien un rôle, c'est celui de régler les problèmes que les villes existantes n'ont pas su résoudre. Nous avons décidé de place notre <i>éponge de Sierpinski</i> sur l'Amanishah Nala afin de pouvoir en faire un point de départ pour ce projet d'utopie urbaine. La totalité du <smart system> est en effet basé sur cette gestion de l'eau , à la fois si précieuse et si peu respectée par les usages locaux. Chacune des places générées par ce plan fractal traite progressivement l'eau, de plus en plus finement, afin de transformer d'une liquide dangereux à une ressource saine et exploitable.<br><br> • Premièrement, toute la partie nord-ouest de la ville est constituée d'une station d'épuration géante, très avancée en matière de traitement primaire de l'eau (retirer les gros débris, filtrer les eaux inexploitables des eaux à retraiter, première désalinisation solaire) <br> •  Le cours d'eau est ensuite redirigé vers la très vaste place centrale, où l'eau sera traitée de manière lente, par décantation et phyto-épuration. A cette étape l'eau sera capable de recevoir des baigneurs, très nombreux du fait de la culture et de la religion indiennes. <br> • La troisième étape guide ses eaux <i>accessibles</i> vers les places intermédiaires, qui sont celles qui traiteront également les eaux de pluie et les eaux usées, grâce à des bassins à l'air libre et des cuves enterrées. <br> • Ces eaux usées proviennent en réalité de la quatrième étape : les petites places stockant l'eau potables en sécurité dans des cuves et récoltant les eaux de moussons dans des bassins publics. <br> • Ces deux types d'eaux <i>propres</i> auront des rôles clés dans la vie de la cité : l'eau potable sera distribuée dans les logements et les bureaux et l'eau de pluie sera pompée sur les toits avant de cheminer à l'air libre jusqu'au sol, créant ainsi un courant d'eau continu dans les <i>couches</i> d'espaces publics surélevés. Cette méthode, associée aux légers courants d'air de Jaipur s'inspire des méthodes de climatisation naturelle des palais et temples indiens. Elle créera un climat au propice à la vie en extérieur, si chère au habitants. <br> • Le dernier aspect de traitement des eaux dans cette cité concerne les eaux non-exploitables, stockées au départ même du parcours, dans la station d'épuration. Ces eaux sont stockées dans des tubes, placés au dessus de la ville. Grâce à l'énergie solaire et au développement d'algues vertes, ce système produira l'énergie de biomasse nécessaire au fonctionnement de toutes les installations de traitements des eaux. <br> <br> Cette ville a également été pensé comme un hydro-data center, rassemblant des informations sur la qualité et la quantité d'eau au fur et à mesure de son parcours afin d'ajuster au mieux les débits et les temps de décantation. <br> <br>L'organisation de la ville a été pensée en <i>couches</i>, produisant l'espace public comme interstices, comme <i>failles climatiques</i>, favorisant le développement de végétation propice à la réduction de la chaleur urbaine. <br> <br> ",
        "images":["img/1vox.jpg","img/2vox.jpg","img/3vox.jpg","img/4vox.jpg","img/5vox.jpg","img/6vox.jpg","img/7vox.jpg","img/8vox.jpg","img/9vox.jpg","img/10vox.jpg","img/11vox.jpg","img/12vox.jpg","img/13vox.jpg","img/14vox.jpg","img/15vox.jpg","img/16vox.jpg","img/17vox.jpg","img/18vox.jpg","img/19vox.jpg",],
        "annee":"2015",
        "miniature":"img/mini/voxel.jpg",
        "miniature_t":"img/mini/voxelb.jpg"
    },
	{
        "titre":"forêt de mellinet ",
        "description_en":"MELLINET'S FOREST • 2015 • <i> with Gwenn Moreau & Ahmat Dallah </i> <br> <br>Little by little, Nantes is getting harder to densify. Potential sites for important housing operation progressively reduce and the former <i>Mellinet casern</i> presents now a great opportunity : how to create 2000 new housing in the city center. <br><br> Each team had to work on a very strong spatial commitment. We decided to focus on a 50/50 use of the parcel : <br><br> • North should be a vast car-free park, reusing existing buildings to house a three-sequence program. Sport fields and gymnasium on West-side, intergenerational activities <i>(meaning retirement house and childcare center)</i> on East-side, and in between the soon-to-be <b> Mellinet's Forest</b>, a partly replanted wood, connecting to the South part of the project. <br> <br> • South part should receive the 2000 housing, connected to the city roads thanks to a ring road and two new limited-access transversal streets. Most of the housing are situated in the 18 towers, based on 6 models of buildings presenting various types of typology and materials but always following a unique global organization : two floors to house shops and public services, 3 floors of parking space creating a cantilevered gallery for the lower floors and a suspended garden for the upper ones, finally the 12 upper floors are made to receive 60/70 housings, trying to decline it in various ways of living and to adapt family mutations. Each street also reach a <i>folie</i>, meaning an outstanding building, following its own rules and presenting unique types of housing and different ways to distribute the floors. Each one of those three buildings houses around 150 housing and aim to mix population and public uses in the neighborhood. <br> <br> ",
        "description_fr": "2015 • <i> avec Gwenn Moreau & Ahmat Dallah </i> <br> <br>La ville de Nantes est de plus en plus difficile à densifier. Le nombre de sites capables de recevoir d'importantes opérations de logement en centre-ville s'amenuise, faisant de l'ancienne <i>caserne militaire de Mellinet</i> une incroyable opportunité pour répondre au programme : créer 2000 logements en cœur de ville. <br><br>Chaque trinôme de travail devait exploiter un principe spatial fort à l'échelle de la parcelle. Nous avons choisi de n'exploiter que 50% de la surface totale disponible pour implanter les logements : <br><br> • Le Nord de la caserne recevra un vaste parc, non-accessible en voiture, où seront réutilisés les bâtiments existants pour installer un programme en trois séquences. Des terrains de sport et un gymnase à l'ouest, des activités intergénérationnelles (crèche, maison de retraite) à l'est. Enfin, entre les deux, la séquence centrale est un bois, en partie replanté, constituant la <i>forêt de Mellinet</i> et faisant lien avec la partie sud du projet. <br> <br> • Les 2000 logements seront implantés au sud, connectés au réseau routier urbain grâce à une route périphérique au projet et à deux voies à accès limité. La majorité des logements sera situé dans 18 tours, basées sur 6 modèles aux typologies et matériaux variés, déclinant tous une organisation générale unique : les 2 premiers niveaux accueilleront commerces et services publics, les 3 suivants sont réservés au parking, créant un galerie en porte à faux pour les commerces en dessous et un jardin surélevé pour les étages supérieurs. Enfin, les 12 derniers étages seront destinés à recevoir les 60 - 70 logements, déclinés en fonction des modes de vie et adaptables aux mutation familiales. Chacune des rues permet aussi d'atteindre un autre type de bâtiments, les <i>folies</i>, possédant chacune des règles d'organisation différentes et un système de distribution particulier. Chacune de ces folies abrite environ 150 logements et propose une manière de mixer les populations et les usages au sein du quartier. <br> <br> ",
        "images":["img/mellinet (31).jpg","img/mellinet (32).png","img/mellinet (33).jpg","img/mellinet (34).jpg","img/mellinet (35).jpg","img/mellinet (36).jpg","img/mellinet (37).jpg","img/mellinet (38).jpg","img/mellinet (39).jpg","img/mellinet (40).jpg","img/mellinet (41).jpg","img/mellinet (42).jpg","img/mellinet (43).jpg","img/mellinet (44).jpg","img/mellinet (45).jpg","img/mellinet (46).jpg","img/mellinet (47).jpg","img/mellinet (48).jpg","img/mellinet (49).jpg","img/mellinet (50).jpg","img/mellinet (51).jpg","img/mellinet (52).jpg"],
        "annee":"2014",
        "miniature":"img/mini/mellinet.jpg",
        "miniature_t":"img/mini/mellinetb.jpg"
    },
	{
        "titre":"quai rouge",
        "description_fr":"RED DOCK • 2015 <br><br> The goal of this student project was to answer a very specific request : create a building to house a <i>nature-oriented</i> center. The purpose was to create a place where could be found classrooms for associations or school trips, various labs, an exhibition room and a vast storehouse for boats, kayaks and other nautical activities. To make it complete, some technical spaces were also required, such as changing rooms or housing for a watchman and his family. A very precise attention had to be paid to structure, materials and features like heating and ventilation systems. <br><br>I decided to conceive the whole project in symbiosis with its surroundings : on one hand, a very green and natural space, with pedestrian walkways and various tree species, on the other hand, a fairly straight artificial channel, very noticeable and yet very calm, in the middle of the site. What stroke me was the intricate relation between the lush vegetation, irregular and unbridled, and the man-made channel with all the rusted machinery of the lock. It seems like they had been struggling against each other for decades, slowly, bit by bit ... You can see plants climbing up the structures and gears popping out the ground.<br><br>The projected buildings shows the rusty appearance of corten steel, looking like it raised from the ground. The whole organization is based on the route taken by the visitors. <br>• One goes up to a sky terrace where it's possible to observe the rich ornithological life of the site by day, and the stars by night. This path required a majestic staircase, looking up to the vast exhibition and reception room. On the ground floor, can also be reached a special class-lab, popping out closed to the channel, giving a very close view to the biodiversity of the surroundings. <br> •The other way digs down, progressively sinking in earth, until the ground line reaches the eye line of the visitor. This path leads to buried classrooms and to the nautical facility, directly opened to the channel. <br><br>",
        "description_en":"2015<br><br><div class='align:center'><i>Première visite du canal de la Martinière, tout est vert, tout est calme.<br>Voilà un bon endroit pour venir pêcher ou pique-niquer entre amis. <br>Des arbres à perte de vue, des roseaux, et cette eau ... si immobile. <br>Et pourtant une présence habite ce site, on la ressent, rien de tout cela n’est vraiment naturel, l’homme y a mis ses doigts, le sol a été manipulé. Certaines machines, aux entrailles visibles, témoignent de cette maîtrise des éléments.</i></div><br>Le végétal n’est pas seul, il existe avec le minéral, avec l’artificiel, ils se soutiennent et s’opposent. Il faut étudier, parcourir tout ce canal pour en mesurer les proportions, comprendre comment il lie l’homme et la nature. <br> Comme les mélodieux habitants du site, il faut s’envoler. <br><br>C’est sur la rive de ce canal, que la base nautique vient s’appuyer. Dans ce site très étendu, la question du rapport de domination entre le bâtiment et son environnement est à se poser. Ce projet affiche un parti pris d’insertion au site très clair. Un espace extérieur protégé, limité par la rive au Sud, trouve sa place entre les trois ailes du projet. Au Nord, le bâtiment se veut contenu dans le paysage, il s’adapte à sa végétation et sa morphologie lui permet de limiter son impact visuel à un soulèvement du sol. Au contraire, ce sol nous dévoile les deux autres bâtiments, au Sud Est et Sud Ouest, comme des preuves de sa manipulation. Ils nous apparaissent strictes et découpés, d’une matérialité froide, liée aux machines de l’écluse. Comme extraits du sol, ces volumes bénéficient d’un rapport direct avec leur environnement aquatique et végétal. <br><br>On pénètre dans la base par le Nord-Est, après avoir longé le canal ou traversé les bois à proximité. Le hall d’accueil est vaste et très vitré, on y accède par une longue rampe qui l’enfonce dans le sol. Ambigu, situé dans une faille entre le bâtiment enterré au Nord et le bâtiment minéral au Sud-Est, cet espace marque la transition vers l’intérieur, il permet d’atteindre les trois parcours majeurs d’utilisation du bâtiment. <br><br>En continuant tout droit depuis le hall, d’Est en Ouest, on pénètre dans un nouvel espace, très ouvert vers le canal au Sud. Cette fois encore le sol a été manipulé, une rampe ascendante fait évoluer la vision de l’eau au fil du parcours et permet de retrouver le niveau extérieur et d’atteindre les équipements sportifs. Depuis ce volume intérieur on peut aussi accéder aux salles de cours au Nord, comme des cavités dont la morphologie intérieure témoigne de leur situation sous-terraine. <br>En se dirigeant vers le Sud depuis le hall, on peut prendre le chemin de la terrasse par un escalier mis en scène et visible depuis l’entrée. Cet escalier offre, au début de son ascension, une vue dégagée sur l’espace extérieur protégé du projet et sur le canal. Mais au gré de la montée, le visiteur perd progressivement cette ouverture visuelle, forgeant un souvenir précis du canal dans sa mémoire avant d’atteindre la terrasse. Cette terrasse est orientée pour donner une vue différente de celle offerte par l’escalier. Elle se tourne vers l’écluse et au Nord, vers la Loire, offrant une nouvelle perception du canal à celui qui la pratique. <br><br>Un  troisième parcours, également visible depuis l’entrée, permet d’atteindre la salle nature et la salle multimédia. Au contraire des deux autres, ce parcours ne permet pas de «monter» ou de «remonter» mais il amène à s’enfoncer plus encore dans le sol pour atteindre le niveau de l’eau. La salle nature, la plus au Sud et la plus proche du canal, entre donc en relation directe avec sa végétation de rive et sa faune. <br><br>Ce projet possède aussi des logements, situés au Sud, aux deuxième et troisième étages, entre la salle nature et la terrasse d’observation. Ils sont accessibles par une entrée particulière située dans l’espace extérieur protégé du projet. <br><br>",
        "images":["img/pell1.jpg","img/pell2.jpg","img/pell3.jpg","img/pell4.jpg","img/pell5.jpg","img/pell6.jpg","img/pell7.jpg","img/pell8.jpg","img/pell9.jpg","img/pell10.jpg","img/pell11.jpg","img/pell12.jpg","img/pell13.jpg","img/pell14.jpg","img/pell15.jpg",],
        "annee":"2014",
        "miniature":"img/mini/quairouge.jpg",
        "miniature_t":"img/mini/quairougeb.jpg"
    },
    {
        "titre":"tenkuu no jima",
        "description_en":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean leo nulla, vulputate at efficitur in, dignissim in neque. Aenean bibendum sollicitudin lorem, et tempus tellus dapibus ut. Nulla iaculis elementum risus vel dignissim. Vestibulum at mollis neque, quis viverra neque. Donec vitae libero finibus, placerat metus sed, gravida est. Duis nec magna ultrices, semper lacus quis, scelerisque ex. Praesent sodales lacinia libero, in pharetra mi bibendum ut. Curabitur eu pharetra purus. Mauris tristique, dolor in lacinia rhoncus, nisl diam congue nisl, a placerat sapien lorem vel dui.		Nam pretium purus id pretium rhoncus. Proin at sem bibendum enim semper auctor. Integer lacinia turpis non justo finibus, gravida lacinia dolor elementum. Fusce tempus tellus at tortor porttitor luctus. Pellentesque imperdiet pharetra laoreet. Maecenas mauris arcu, porttitor in ipsum at, feugiat egestas augue. Fusce eu ipsum vel arcu sodales aliquam eu quis elit.			Mauris dictum maximus purus nec facilisis. Duis sit amet magna ut mauris elementum blandit at eget est. Duis rutrum dapibus justo eget placerat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas et urna sit amet metus facilisis semper. Aenean tristique viverra convallis. Cras urna magna, pharetra vitae fringilla id, porttitor faucibus ligula. Nulla at ipsum eu felis dictum eleifend. Etiam neque enim, elementum vitae cursus pharetra, iaculis sollicitudin diam. Donec cursus condimentum arcu at volutpat. Ut efficitur sit amet ex ac pellentesque. Phasellus lobortis consectetur leo in sagittis. Sed consectetur lacinia orci varius aliquet. Aenean sollicitudin nunc nec purus venenatis, quis semper elit gravida. Etiam eu sagittis neque. Fusce at luctus metus, quis dignissim sem.",
        "description_fr":"ifebnfkzebjehzbdjz",
        "images":["img/tenkuu (1).jpg","img/tenkuu (2).jpg","img/tenkuu (3).jpg","img/tenkuu (4).jpg","img/tenkuu (5).jpg","img/tenkuu (6).jpg","img/tenkuu (7).jpg","img/tenkuu (8).jpg","img/tenkuu (9).jpg","img/tenkuu (10).jpg","img/tenkuu (11).jpg","img/tenkuu (12).jpg","img/tenkuu (13).jpg","img/tenkuu (14).jpg","img/tenkuu (15).jpg","img/tenkuu (16).jpg","img/tenkuu (17).jpg","img/tenkuu (18).jpg","img/tenkuu (19).jpg","img/tenkuu (20).jpg","img/tenkuu (21).jpg","img/tenkuu (22).jpg","img/tenkuu (23).jpg","img/tenkuu (24).jpg","img/tenkuu (25).jpg","img/tenkuu (26).jpg",],
        "annee":"2013",
        "miniature":"img/mini/tenkuu.jpg",
        "miniature_t":"img/mini/tenkuub.jpg"
    },
    {
        "titre":"les ouches suspendues",
        "description_en":"une description",
        "description_fr":"ifebnfkzebjehzbdjz",
        "images":["img/imagetest.png","img/imagetest.png","img/imagetest.png","img/imagetest.png"],
        "annee":"2013",
        "miniature":"img/mini/ouches.jpg",
        "miniature_t":"img/mini/ouchesb.jpg"
    },
    {
        "titre":"analyse : casa arnold",
        "description_en":"une description",
        "description_fr":"ifebnfkzebjehzbdjz",
        "images":["img/mario (1).jpg","img/mario (2).jpg","img/mario (3).jpg","img/mario (4).jpg","img/mario (5).jpg","img/mario (6).jpg","img/mario (7).jpg","img/mario (8).jpg","img/mario (9).jpg","img/mario (10).jpg","img/mario (11).jpg","img/mario (12).jpg","img/mario (13).jpg","img/mario (14).jpg","img/mario (15).jpg","img/mario (16).jpg","img/mario (17).jpg","img/mario (18).jpg","img/mario (19).jpg","img/mario (20).jpg","img/mario (21).jpg",],
        "annee":"2012",
        "miniature":"img/mini/campi.jpg",
        "miniature_t":"img/mini/campib.jpg"
    },
    {
        "titre":"la place de la diligence",
        "description_en":"une description",
        "description_fr":"ifebnfkzebjehzbdjz",
        "images":["img/dil 0.jpg","img/dil 1.jpg","img/dili 0.jpg","img/dili 1.jpg","img/dili 2.jpg","img/dili 3.jpg","img/dili 4.jpg","img/dili 5.jpg","img/dili 6.jpg","img/dili 7.jpg","img/dili 8.jpg","img/dili 9.jpg","img/dili 10.jpg","img/dili 11.jpg","img/dili 12.jpg","img/dili 13.jpg","img/dili 14.jpg","img/dili 15.jpg","img/dili 16.jpg","img/dili 17.jpg",],
        "annee":"2014",
        "miniature":"img/mini/diligence.jpg",
        "miniature_t":"img/mini/diligenceb.jpg"
    },
    {
        "titre":"pourvu qu'il pleuve",
        "description_en":"une description",
        "description_fr":"ifebnfkzebjehzbdjz",
        "images":["img/para 0.png","img/para 1.jpg","img/para 2.jpg","img/para 3.jpg","img/para 4.jpg","img/para 5.jpg","img/para 6.jpg","img/para 7.jpg","img/para 8.jpg","img/para 9.jpg","img/para 10.jpg","img/para 11.jpg","img/para 12.jpg","img/para 13.jpg","img/para 14.jpg","img/para 15.jpg","img/para 16.jpg","img/para 17.jpg","img/para 18.jpg","img/para 19.jpg","img/para 20.jpg",],
        "annee":"2014",
        "miniature":"img/mini/parapluie.jpg",
        "miniature_t":"img/mini/parapluieb.jpg"
    },
    {
        "titre":"vhs",
        "description_en":"une description",
        "description_fr":"ifebnfkzebjehzbdjz",
        "images":["img/VHS (1).jpg","img/VHS (2).jpg","img/VHS (3).jpg","img/VHS (4).jpg","img/VHS (5).jpg","img/VHS (6).jpg","img/VHS (7).jpg","img/VHS (8).jpg","img/VHS (9).jpg","img/VHS (10).jpg","img/VHS (11).jpg","img/VHS (12).jpg","img/VHS (13).jpg",],
        "annee":"2013",
        "miniature":"img/mini/vhs.jpg",
        "miniature_t":"img/mini/vhsb.jpg"
    },
];

var publications = [
    {
       "titre":"détruire et construire, la ville à l'écran",
        "description_en":"<div class='alignright'><b>Master thesis</b>, published in Nantes Architecture School's library<br> Available in french on <a href='http://dumas.ccsd.cnrs.fr/dumas-01315765/document'> Dumas - CNRS </a></div><br><br> DESTROY AND BUILD, CITY ON SCREEN • 2015 <br> <br> Representation of cities has always been a classical subject, especially when it comes to seventh art. Indeed, cinema has always found itself as one of the  best tools to build a big-scale representation of a city. . <br> <br> This master thesis is particular in the way it approaches the matter, through a singular point of view. The thought process found its basis in a precise cinematographic corpus : general public movies where can be found scenes of city destruction (disasters movies, war or action movies, blockbusters,...). By focusing on a reduced number of cities and on the way they can be seen on screen, it was possible to spot the different technical processes and their impact on the public. Destruction, as a complementary subject, brings some new elements to understand how cities are built on screen. Those various movies show the city how it wants to be seen, linking its real History to its representation's one, connecting its contemporary urbanism to its altered virtual image, confronting the city to its own decline. <br> <br> <b>Destroying the city on screen to build it on people's mind, study of a city revealing itself through its Image.</b> <br> <br> ",
        "description_fr":"<div class='alignright'><b>Mémoire de master</b>, publié dans la bibliothèque de l'ensanantes<br> Consultable sur <a href='http://dumas.ccsd.cnrs.fr/dumas-01315765/document'> Dumas - CNRS </a></div> <br><br>2015<br><br> La question de la représentation de la ville et de son architecture constitue un sujet de réflexion récurrent, notamment dans sa dimension cinématographique. En effet, le Septième Art s’est toujours imposé comme l’un des outils les plus efficaces en ce qui concerne la communication de l’image d’une ville à grande échelle. <br><br>Ce travail de mémoire possède la particularité d’aborder la question sous un axe singulier. La réflexion a trouvé ses bases dans l’étude d’un corpus cinématographie précis : les ouvrages grand public mettant en scène des destructions de ville (films catastrophes, films de guerre ou d’action, etc.). C’est l’intérêt porté à un certain nombre de villes et la manière dont elles sont présentées à l’écran qui ont permis de repérer les différents processus développés et leurs impacts sur le spectateur. La destruction, comme sujet complémentaire, apporte elle aussi son lot d’éléments de compréhension des modes de construction de la ville à l’écran. Ces ouvrages révèlent la ville telle qu’elle veut apparaître en reliant son Histoire à celle de son image, en connectant l’urbanisme contemporain à son aspect virtuel altéré, en confrontant la cité à sa propre Ruine. <br><br> <b>Détruire la ville à l’écran pour la construire dans l’esprit, étude d’une cité qui se dévoile par son image.</b><br> <br> ",
        "images":["img/memoire (0).jpg","img/memoire (1).jpg","img/memoire (2).jpg","img/memoire (3).jpg","img/memoire (4).jpg","img/memoire (5).jpg","img/memoire (6).jpg","img/memoire (7).jpg","img/memoire (8).jpg",],
        "annee":"2015",
        "miniature":"img/mini/memoire.jpg" ,
        "miniature_t":"img/mini/memoireb.jpg"
    },
    ];


var fond = [
    {
        "nom":"Photo :  Vitrahaus - Weil am Rhein",
        "image":"img/fond/vitrahaus.jpg"
    },
    {
        "nom":"Photo : Musée juif - Berlin",
        "image":"img/fond/museejuifs.jpg"
    },
	{
        "nom":"Photo : Saint Charles aux Quatre Fontaines - Rome",
        "image":"img/fond/quatrefontaines.jpg"
    },
	{
        "nom":"Photo :  Musée Kunsthalle - Rotterdam",
        "image":"img/fond/kunsthalle.jpg"
    },
    {
        "nom":"Photo : Musée MAS - Anvers",
        "image":"img/fond/mas.jpg"
    },
	{
        "nom":"Photo : Gare de Lisbonne-Oriente - Lisbonne",
        "image":"img/fond/garelisb.jpg"
    },
	{
        "nom":"Photo : Lloyd's Building - Londres",
        "image":"img/fond/londres.jpg"
    },
	{
        "nom":"Photo : Musée MAS - Anvers",
        "image":"img/fond/mas.jpg"
    },
	{
        "nom":"Photo : Tour Eiffel - Paris",
        "image":"img/fond/eiffel.jpg"
    },
	{
        "nom":"Photo : Temple du Goût - Nantes",
        "image":"img/fond/templegout.jpg"
    },
	{
        "nom":"Photo : Musée NAI - Rotterdam",
        "image":"img/fond/nai.jpg"
    },
	{
        "nom":"Photo : Musée MAXXI - Rome",
        "image":"img/fond/maxi.jpg"
    },
	{
        "nom":"Photo : British Museum - Londres",
        "image":"img/fond/britmuseum.jpg"
    },
];

var meta_text = {
    "boiteGrosTitreLigne1_fr":"ARCHITECTURE",
    "boiteGrosTitreLigne1_en":"ARCHITECTURE",
    "boiteGrosTitreLigne2_en":"ENGINEERING",
    "boiteGrosTitreLigne2_fr":"INGENIERIE",
    "compet1_fr":"architecture •workshops",
    "compet1_en":"architecture •workshops",
    "compet2_fr":"publications •graphisme",
    "compet2_en":"publications •graphism",
    "compet3_fr":"portrait •compétences",
    "compet3_en":"profile •skills",
    "boitePetitTitreLigne1_fr":"Portfolio en ligne",
    "boitePetitTitreLigne1_en":"Online portfolio",
    "boitePetitTitreLigne2_fr":"<i>Site en construction</i>",
    "boitePetitTitreLigne2_en":"<i>Website under construction</i>"
};
