var projets = [
    {
        "titre":"v0xel",
        "description_en":"V0XEL • 2015 • <i> with Charles Poulain & Chun Hung </i> <br> <br> India is starting a great plan to create more than 100 smart cities in the very next years. Prime Minister Narendra Modi has chosen various sites and existing cities to receive those soon-to-be <i>smart cities</i>. Jaipur is the capital city of Rajhastan and has grown down a mountain. The historic center, very symetric and square-based, has expanded to the South, leading the city to build a bright new ring road around Jaipur. <br> <br> Water is very rare in this part of the world, and the monsoon is quick and not as abundant as it is in many tropical countries. The only stream running through the city is th Amanishah Nala. Born in the mountain, this little river goes down to South and, not only is it salted and non-drinkable but it also carries every piece of garbage produced by the city, or chemicals delivered by dyeing industries. <br> <br> Because smart cities only exist to deal with the issues met by existing ones, we decided to place our <i>Sierpinski Sponge</i> on this Amanishah Nala river to use it as a starting point for this utopian project. The whole smart system is actually based on this water, so precious but yet so mistreated by the rest of Jaipur. Every place generated by the fractal master plan enables to progressively treat it in order to make it pass from a poison-like liquid to a drinkable/healthy strength for the population. <br><br> • First, North West of this city is made of a treatment plant, removing the biggest pieces of rubbish and desalinating part of the water. <br> • The stream is then directed to the vast center place, where phyto-treatment enables people to bathe in it, which is very important among Indian culture. <br> • The third step directs  water to medium places, treating rainwater and sewage. <br> • This sewage actually comes back from the fourth step : places storing drinkable water underground and gathering rainwater on public basins. <br> • Those two types of water then receive different roles in the city : drinkable water is directed in the housing and working spaces while the rainwater is used to reduce the urban heat. Culturally, a stream of water is often used in India to create a natural ventilation in palaces and temples. The same logic has been used here, pumping the fresh water up the roof and then letting it pour down to the ground basins, associating to draughts to refresh the public spaces' layers. <br> • Last aspect of this water cycle is about the water that was too dirty to be decontaminated. The latter is used in solar tubes, with special algae to produce biomass energy from solar power. <br> <br> The city is imagined to gather data on water levels and salinity in order to adapt the channels debit to let the water decant long enough on every places. <br> <br> To organize urban repartition, the spaces have been thought as layers, producing public <i>voids</i> where water can run and vegetation star to grow.<br><br>",
        "description_fr":"ifebnfkzebjehzbdjz",
        "images":["img/1vox.jpg","img/2vox.jpg","img/3vox.jpg","img/4vox.jpg","img/5vox.jpg","img/6vox.jpg","img/7vox.jpg","img/8vox.jpg","img/9vox.jpg","img/10vox.jpg","img/11vox.jpg","img/12vox.jpg","img/13vox.jpg","img/14vox.jpg","img/15vox.jpg","img/16vox.jpg","img/17vox.jpg","img/18vox.jpg","img/19vox.jpg",],
        "annee":"2015",
        "miniature":"img/mini/voxel.jpg",
        "miniature_t":"img/mini/voxelb.jpg"
    },
	{
        "titre":"forêt de mellinet ",
        "description_en":"MELLINET'S FOREST • 2015 • <i> with Gwenn Moreau & Ahmat Dallah </i> <br> <br>Little by little, Nantes is getting harder to densify. Potential sites for important housing operation progressively reduce and the former <i>Mellinet casern</i> presents now a great opportunity : how to create 2000 new housing in the city center. <br><br> Each team had to work on a very strong spatial commitment. We decided to focus on a 50/50 use of the parcel : <br><br> • North should be a vast car-free park, reusing existing buildings to house a three-sequence program. Sport fields and gymnasium on West-side, intergenerational activities <i>(meaning retirement house and childcare center)</i> on East-side, and in between the soon-to-be <b> Mellinet's Forest</b>, a partly replanted wood, connecting to the South part of the project. <br> <br> • South part should receive the 2000 housing, connected to the city roads thanks to a ring road and two new limited-access transversal streets. Most of the housing are situated in the 18 towers, based on 6 models of buildings presenting various types of typology and materials but always following a unique global organization : two floors to house shops and public services, 3 floors of parking space creating a cantilevered gallery for the lower floors and a suspended garden for the upper ones, finally the 12 upper floors are made to receive 60/70 housings, trying to decline it in various ways of living and to adapt family mutations. Each street also reach a <i>folie</i>, meaning an outstanding building, following its own rules and presenting unique types of housing and different ways to distribute the floors. Each one of those three buildings houses around 150 housing and aim to mix population and public uses in the neighborhood. <br> <br> ",
        "description_fr":"ifebnfkzebjehzbdjz",
        "images":["img/mellinet (1).jpg","img/mellinet (2).jpg","img/mellinet (3).jpg","img/mellinet (4).jpg","img/mellinet (5).jpg","img/mellinet (6).jpg","img/mellinet (7).jpg","img/mellinet (8).jpg","img/mellinet (9).jpg","img/mellinet (10).jpg","img/mellinet (11).jpg","img/mellinet (12).jpg","img/mellinet (13).jpg","img/mellinet (14).jpg","img/mellinet (15).jpg","img/mellinet (16).jpg","img/mellinet (17).jpg","img/mellinet (18).jpg","img/mellinet (19).jpg","img/mellinet (20).jpg","img/mellinet (21).jpg","img/mellinet (22).jpg","img/mellinet (23).jpg"],
        "annee":"2014",
        "miniature":"img/mini/mellinet.jpg",
        "miniature_t":"img/mini/mellinetb.jpg"
    },
	{
        "titre":"quai rouge",
        "description_en":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean leo nulla, vulputate at efficitur in, dignissim in neque. Aenean bibendum sollicitudin lorem, et tempus tellus dapibus ut. Nulla iaculis elementum risus vel dignissim. Vestibulum at mollis neque, quis viverra neque. Donec vitae libero finibus, placerat metus sed, gravida est. Duis nec magna ultrices, semper lacus quis, scelerisque ex. Praesent sodales lacinia libero, in pharetra mi bibendum ut. Curabitur eu pharetra purus. Mauris tristique, dolor in lacinia rhoncus, nisl diam congue nisl, a placerat sapien lorem vel dui.		Nam pretium purus id pretium rhoncus. Proin at sem bibendum enim semper auctor. Integer lacinia turpis non justo finibus, gravida lacinia dolor elementum. Fusce tempus tellus at tortor porttitor luctus. Pellentesque imperdiet pharetra laoreet. Maecenas mauris arcu, porttitor in ipsum at, feugiat egestas augue. Fusce eu ipsum vel arcu sodales aliquam eu quis elit.			Mauris dictum maximus purus nec facilisis. Duis sit amet magna ut mauris elementum blandit at eget est. Duis rutrum dapibus justo eget placerat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas et urna sit amet metus facilisis semper. Aenean tristique viverra convallis. Cras urna magna, pharetra vitae fringilla id, porttitor faucibus ligula. Nulla at ipsum eu felis dictum eleifend. Etiam neque enim, elementum vitae cursus pharetra, iaculis sollicitudin diam. Donec cursus condimentum arcu at volutpat. Ut efficitur sit amet ex ac pellentesque. Phasellus lobortis consectetur leo in sagittis. Sed consectetur lacinia orci varius aliquet. Aenean sollicitudin nunc nec purus venenatis, quis semper elit gravida. Etiam eu sagittis neque. Fusce at luctus metus, quis dignissim sem.",
        "description_fr":"ifebnfkzebjehzbdjz",
        "images":["img/pell1.jpg","img/pell2.jpg","img/pell3.jpg","img/pell4.jpg","img/pell5.jpg","img/pell6.jpg","img/pell7.jpg","img/pell8.jpg","img/pell9.jpg","img/pell10.jpg","img/pell11.jpg","img/pell12.jpg","img/pell13.jpg","img/pell14.jpg","img/pell15.jpg",],
        "annee":"2014",
        "miniature":"img/mini/quairouge.jpg",
        "miniature_t":"img/mini/quairougeb.jpg"
    },
    {
        "titre":"tenkuu no jima",
        "description_en":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean leo nulla, vulputate at efficitur in, dignissim in neque. Aenean bibendum sollicitudin lorem, et tempus tellus dapibus ut. Nulla iaculis elementum risus vel dignissim. Vestibulum at mollis neque, quis viverra neque. Donec vitae libero finibus, placerat metus sed, gravida est. Duis nec magna ultrices, semper lacus quis, scelerisque ex. Praesent sodales lacinia libero, in pharetra mi bibendum ut. Curabitur eu pharetra purus. Mauris tristique, dolor in lacinia rhoncus, nisl diam congue nisl, a placerat sapien lorem vel dui.		Nam pretium purus id pretium rhoncus. Proin at sem bibendum enim semper auctor. Integer lacinia turpis non justo finibus, gravida lacinia dolor elementum. Fusce tempus tellus at tortor porttitor luctus. Pellentesque imperdiet pharetra laoreet. Maecenas mauris arcu, porttitor in ipsum at, feugiat egestas augue. Fusce eu ipsum vel arcu sodales aliquam eu quis elit.			Mauris dictum maximus purus nec facilisis. Duis sit amet magna ut mauris elementum blandit at eget est. Duis rutrum dapibus justo eget placerat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas et urna sit amet metus facilisis semper. Aenean tristique viverra convallis. Cras urna magna, pharetra vitae fringilla id, porttitor faucibus ligula. Nulla at ipsum eu felis dictum eleifend. Etiam neque enim, elementum vitae cursus pharetra, iaculis sollicitudin diam. Donec cursus condimentum arcu at volutpat. Ut efficitur sit amet ex ac pellentesque. Phasellus lobortis consectetur leo in sagittis. Sed consectetur lacinia orci varius aliquet. Aenean sollicitudin nunc nec purus venenatis, quis semper elit gravida. Etiam eu sagittis neque. Fusce at luctus metus, quis dignissim sem.",
        "description_fr":"ifebnfkzebjehzbdjz",
        "images":["img/tenkuu (1).jpg","img/tenkuu (2).jpg","img/tenkuu (3).jpg","img/tenkuu (4).jpg","img/tenkuu (5).jpg","img/tenkuu (6).jpg","img/tenkuu (7).jpg","img/tenkuu (8).jpg","img/tenkuu (9).jpg","img/tenkuu (10).jpg","img/tenkuu (11).jpg","img/tenkuu (12).jpg","img/tenkuu (13).jpg","img/tenkuu (14).jpg","img/tenkuu (15).jpg","img/tenkuu (16).jpg","img/tenkuu (17).jpg","img/tenkuu (18).jpg","img/tenkuu (19).jpg","img/tenkuu (20).jpg","img/tenkuu (21).jpg","img/tenkuu (22).jpg","img/tenkuu (23).jpg","img/tenkuu (24).jpg","img/tenkuu (25).jpg","img/tenkuu (26).jpg",],
        "annee":"2013",
        "miniature":"img/mini/tenkuu.jpg",
        "miniature_t":"img/mini/tenkuub.jpg"
    },
    {
        "titre":"les ouches suspendues",
        "description_en":"une description",
        "description_fr":"ifebnfkzebjehzbdjz",
        "images":["img/imagetest.png","img/imagetest.png","img/imagetest.png","img/imagetest.png"],
        "annee":"2013",
        "miniature":"img/mini/ouches.jpg",
        "miniature_t":"img/mini/ouchesb.jpg"
    },
    {
        "titre":"analyse : casa arnold",
        "description_en":"une description",
        "description_fr":"ifebnfkzebjehzbdjz",
        "images":["img/mario (1).jpg","img/mario (2).jpg","img/mario (3).jpg","img/mario (4).jpg","img/mario (5).jpg","img/mario (6).jpg","img/mario (7).jpg","img/mario (8).jpg","img/mario (9).jpg","img/mario (10).jpg","img/mario (11).jpg","img/mario (12).jpg","img/mario (13).jpg","img/mario (14).jpg","img/mario (15).jpg","img/mario (16).jpg","img/mario (17).jpg","img/mario (18).jpg","img/mario (19).jpg","img/mario (20).jpg","img/mario (21).jpg",],
        "annee":"2012",
        "miniature":"img/mini/campi.jpg",
        "miniature_t":"img/mini/campib.jpg"
    },
    {
        "titre":"la place de la diligence",
        "description_en":"une description",
        "description_fr":"ifebnfkzebjehzbdjz",
        "images":["img/dil 0.jpg","img/dil 1.jpg","img/dili 0.jpg","img/dili 1.jpg","img/dili 2.jpg","img/dili 3.jpg","img/dili 4.jpg","img/dili 5.jpg","img/dili 6.jpg","img/dili 7.jpg","img/dili 8.jpg","img/dili 9.jpg","img/dili 10.jpg","img/dili 11.jpg","img/dili 12.jpg","img/dili 13.jpg","img/dili 14.jpg","img/dili 15.jpg","img/dili 16.jpg","img/dili 17.jpg",],
        "annee":"2014",
        "miniature":"img/mini/diligence.jpg",
        "miniature_t":"img/mini/diligenceb.jpg"
    },
    {
        "titre":"pourvu qu'il pleuve",
        "description_en":"une description",
        "description_fr":"ifebnfkzebjehzbdjz",
        "images":["img/para 0.png","img/para 1.jpg","img/para 2.jpg","img/para 3.jpg","img/para 4.jpg","img/para 5.jpg","img/para 6.jpg","img/para 7.jpg","img/para 8.jpg","img/para 9.jpg","img/para 10.jpg","img/para 11.jpg","img/para 12.jpg","img/para 13.jpg","img/para 14.jpg","img/para 15.jpg","img/para 16.jpg","img/para 17.jpg","img/para 18.jpg","img/para 19.jpg","img/para 20.jpg",],
        "annee":"2014",
        "miniature":"img/mini/parapluie.jpg",
        "miniature_t":"img/mini/parapluieb.jpg"
    },
    {
        "titre":"vhs",
        "description_en":"une description",
        "description_fr":"ifebnfkzebjehzbdjz",
        "images":["img/VHS (1).jpg","img/VHS (2).jpg","img/VHS (3).jpg","img/VHS (4).jpg","img/VHS (5).jpg","img/VHS (6).jpg","img/VHS (7).jpg","img/VHS (8).jpg","img/VHS (9).jpg","img/VHS (10).jpg","img/VHS (11).jpg","img/VHS (12).jpg","img/VHS (13).jpg",],
        "annee":"2013",
        "miniature":"img/mini/vhs.jpg",
        "miniature_t":"img/mini/vhsb.jpg"
    },
];

var publications = [
    {
       "titre":"détruire et construire, la ville à l'écran",
        "description_en":"<b>Master thesis</b>, published in Nantes Architecture School's library<br> Available in french on http://dumas.ccsd.cnrs.fr/dumas-01315765/document<br><br> DESTROY AND BUILD, CITY ON SCREEN • 2015 <br> <br> Representation of cities has always been a classical subject, especially when it comes to seventh art. Indeed, cinema has always found itself as one of the  best tools to build a big-scale representation of a city. . <br> <br> This master thesis is particular in the way it approaches the matter, through a singular point of view. The thought process found its basis in a precise cinematographic corpus : general public movies where can be found scenes of city destruction (disasters movies, war or action movies, blockbusters,...). By focusing on a reduced number of cities and on the way they can be seen on screen, it was possible to spot the different technical processes and their impact on the public. Destruction, as a complementary subject, brings some new elements to understand how cities are built on screen. Those various movies show the city how it wants to be seen, linking its real History to its representation's one, connecting its contemporary urbanism to its altered virtual image, confronting the city to its own decline. <br> <br> <b>Destroying the city on screen to build it on people's mind, study of a city revealing itself through its Image.</b> <br> <br> ",
        "description_fr":"<b>Mémoire de master, publié dans la bibliothèque de l'ensanantes</b> <br> Consultable sur http://dumas.ccsd.cnrs.fr/dumas-01315765/document <br><br><br>2015<br> La question de la représentation de la ville et de son architecture constitue un sujet de réflexion récurrent, notamment dans sa dimension cinématographique. En effet, le Septième Art s’est toujours imposé comme l’un des outils les plus efficaces en ce qui concerne la communication de l’image d’une ville à grande échelle. <br><br>Ce travail de mémoire possède la particularité d’aborder la question sous un axe singulier. La réflexion a trouvé ses bases dans l’étude d’un corpus cinématographie précis : les ouvrages grand public mettant en scène des destructions de ville (films catastrophes, films de guerre ou d’action, etc.). C’est l’intérêt porté à un certain nombre de villes et la manière dont elles sont présentées à l’écran qui ont permis de repérer les différents processus développés et leurs impacts sur le spectateur. La destruction, comme sujet complémentaire, apporte elle aussi son lot d’éléments de compréhension des modes de construction de la ville à l’écran. Ces ouvrages révèlent la ville telle qu’elle veut apparaître en reliant son Histoire à celle de son image, en connectant l’urbanisme contemporain à son aspect virtuel altéré, en confrontant la cité à sa propre Ruine. <br><br> <b>Détruire la ville à l’écran pour la construire dans l’esprit, étude d’une cité qui se dévoile par son image.</b><br> <br> ",
        "images":["img/memoire (0).jpg","img/memoire (1).jpg","img/memoire (2).jpg","img/memoire (3).jpg","img/memoire (4).jpg","img/memoire (5).jpg","img/memoire (6).jpg","img/memoire (7).jpg","img/memoire (8).jpg",],
        "annee":"2015",
        "miniature":"img/mini/memoire.jpg" ,
        "miniature_t":"img/mini/memoireb.jpg"
    },
    ];


var fond = [
    {
        "nom":"Photo :  Vitrahaus - Weil am Rhein",
        "image":"img/fond/vitrahaus.jpg"
    },
    {
        "nom":"Photo : Musée juif - Berlin",
        "image":"img/fond/museejuifs.jpg"
    },
	{
        "nom":"Photo : Saint Charles aux Quatre Fontaines - Rome",
        "image":"img/fond/quatrefontaines.jpg"
    },
	{
        "nom":"Photo :  Musée Kunsthalle - Rotterdam",
        "image":"img/fond/kunsthalle.jpg"
    },
    {
        "nom":"Photo : Musée MAS - Anvers",
        "image":"img/fond/mas.jpg"
    },
	{
        "nom":"Photo : Gare de Lisbonne-Oriente - Lisbonne",
        "image":"img/fond/garelisb.jpg"
    },
	{
        "nom":"Photo : Lloyd's Building - Londres",
        "image":"img/fond/londres.jpg"
    },
	{
        "nom":"Photo : Musée MAS - Anvers",
        "image":"img/fond/mas.jpg"
    },
	{
        "nom":"Photo : Tour Eiffel - Paris",
        "image":"img/fond/eiffel.jpg"
    },
	{
        "nom":"Photo : Temple du Goût - Nantes",
        "image":"img/fond/templegout.jpg"
    },
	{
        "nom":"Photo : Musée NAI - Rotterdam",
        "image":"img/fond/nai.jpg"
    },
	{
        "nom":"Photo : Musée MAXXI - Rome",
        "image":"img/fond/maxi.jpg"
    },
	{
        "nom":"Photo : British Museum - Londres",
        "image":"img/fond/britmuseum.jpg"
    },
];

var meta_text = {
    "boiteGrosTitreLigne1_fr":"ARCHITECTURE",
    "boiteGrosTitreLigne1_en":"ARCHITECTURE",
    "boiteGrosTitreLigne2_en":"ENGINEERING",
    "boiteGrosTitreLigne2_fr":"INGENIERIE",
    "compet1_fr":"architecture •workshops",
    "compet1_en":"architecture •workshops",
    "compet2_fr":"publications •graphisme",
    "compet2_en":"publications •graphism",
    "compet3_fr":"portrait •compétences",
    "compet3_en":"profile •skills",
    "boitePetitTitreLigne1_fr":"Portfolio en ligne",
    "boitePetitTitreLigne1_en":"Online portfolio",
    "boitePetitTitreLigne2_fr":"<i>Site en construction</i>",
    "boitePetitTitreLigne2_en":"<i>Website under construction</i>"
};
